### ISSUE TITLE
cannot export to json-ld from scaffold-test 

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#65]
Not sure what is going wrong but I can't export the scaffold-test model to json-ld, so can't load to scigraph.
```
An unexpected error occurred: Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231183:22) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231209:25) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231191:23) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231209:25) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231191:23) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231209:25) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231191:23) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231209:25) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231191:23) at Object.../node_modules/jsonld/dist/node6/lib/util.js.api.clone (https://open-physiology-viewer.surge.sh/index.js:231209:25)
```

**Comment by albatros13** [comment]
There is no implementation of scaffold export to JSON-LD, entitiesToJSONLD has to be revised to generate @context and @graph for scaffold resources.
